FROM golang:1.18-bullseye as builder

ENV APP_HOME /go/src/hasmail

WORKDIR "$APP_HOME"
COPY . .

RUN go mod download
RUN go mod verify
RUN go build ./cmd/mailservice

FROM golang:1.18-bullseye

ENV APP_HOME /go/src/hasmail
RUN mkdir -p "$APP_HOME"
WORKDIR "$APP_HOME"

COPY --from=builder "$APP_HOME"/mailservice $APP_HOME
EXPOSE 8000
CMD ["./mailservice"]
