name: golangci-lint
on:
  push:
    branches: [ "main" ]
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17 # TODO: change to 1.18 when most linters support it, see https://github.com/golangci/golangci-lint/issues/2649
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
